FROM python:3.10-bullseye
RUN python -m pip install --upgrade pip
ADD https://github.com/ufoscout/docker-compose-wait/releases/download/2.9.0/wait /wait
RUN chmod +x /wait
WORKDIR /deps
COPY requirements.txt requirements.txt
RUN python -m pip install -r requirements.txt

# Added command to install node.js and npm
RUN curl -sL https://deb.nodesource.com/setup_12.x | bash - && apt-get install -y nodejs

# Added commands to install chart.js and react-chartjs-2
RUN npm install chart.js react-chartjs-2

WORKDIR /app
# CMD /wait && uvicorn main:app --reload --host 0.0.0.0

# If you're using a relational database and want migrations
# to be run automatically, delete the previous CMD line and
# uncomment this CMD line
CMD /wait && python -m migrations up && uvicorn main:app --reload --host 0.0.0.0 --port 80
